sonar.projectKey=task-manager
sonar.projectName=Task Management System
sonar.projectVersion=1.0

sonar.sources=Backend,Frontend/src
sonar.tests=Backend.Tests
sonar.exclusions=**/Migrations/**,**/bin/**,**/obj/**,**/node_modules/**,**/dist/**

sonar.cs.analyzer.projectOutPaths=Backend/bin,Backend.Tests/bin
sonar.javascript.lcov.reportPaths=Frontend/coverage/lcov.info
